### ISSUE TITLE
sund2b rootLabel malfunction when tooltip option used

### ISSUE THREAD

**Issue by dboko** [timelyportfolio/sunburstR#100]
Hello, 

Thanks for your work. I'm a beginner at this. I'm noticing that I can easily change the root label when not using the tooltip option. However, when I use the tooltip option I cannot alter the root label. 

Thank you,
Denis

This is my code:
sund2b(sequences, breadcrumbs = sund2bBreadcrumb(
    html = htmlwidgets::JS("
function(nodedata, size, percent) {
  return '<span style=\"font-weight: bold;\">' + nodedata.name + '</span>' + ' '
}
    ")
) ,tooltip = sund2bTooltip(
    html = htmlwidgets::JS("
function(nodedata) {
  return '<span style=\"font-weight: regular;\">' + nodedata.name + '</span>' + ' '
}
    ")
), rootLabel="change")

**Comment by timelyportfolio** [comment]
@dboko very good question, and I can see how this could be confusing.  Based on how `d2b` works `rootLabel` sets a property `label` on the root node (see [lines](https://github.com/timelyportfolio/sunburstR/blob/master/inst/htmlwidgets/sund2b.js#L70-L72)).  If we override the tooltip or breadcrumb with a function, we'll need to add some logic to choose `label` instead of `name` for root.

```
sund2b(
  sequences,
  breadcrumbs = sund2bBreadcrumb(
    html = htmlwidgets::JS(
"
function(nodedata, size, percent) {
  return '<span style=\"font-weight: bold;\">' + (nodedata.name === 'root' ? nodedata.label : nodedata.name)  + '' + ' '
}
"
    )
  ),
  tooltip = sund2bTooltip(
    html = htmlwidgets::JS(
"
function(nodedata) {
  return '<span style=\"font-weight: bold;\">' + (nodedata.name === 'root' ? nodedata.label : nodedata.name)  + '' + ' '
}
"
    )
  )
  ,rootLabel = "change"
)

```

**Comment by dboko** [comment]
This is great, thank you very much!
