### ISSUE TITLE
Return instance

### ISSUE THREAD

**Issue by GiovanninoPaneEvino** [timelyportfolio/sunburstR#19]
Hello,
First of all, believe it or not - I am a big fan of your work. In recent months I have been starting to create my own widgets at work and I have been following yours as inspiration!

Question ( not an issue, just a curiosity) : why do you return the instance at line 552 of sunburst.js? Instance is not already defined in the factory and reassigned in the renderValue?

Probably I ask it since to me the receiver of the object {Rendervalue:...,Resize:..} is black magic :-)

Thanks,
 Giovanni

**Comment by timelyportfolio** [comment]
Was just looking through email and realized I did not respond.  Sorry for
the delay.  So great to hear from you.  I will try to provide some examples
and also verify that I have not made a mistake ;). The new factory pattern
provides us some advantages and allows use of htmlwidgets as standalone
components.

Thanks again for the email and I will get back in touch soon.

Kent

**Comment by timelyportfolio** [comment]
@GiovanninoPaneEvino sorry this took so long, and I hope you are still interested.  I'll start by warning that I still don't have a favorite pattern for this.  Often I want to manipulate the `htmlwidget` post render in JavaScript.  However, this is often impossible because many of the variables are within the scope closure of `renderValue` and `resize`.  By returning `instance` with `renderValue` and `resize`, we can get access to values that are within the closures of those two functions.  In other cases, I have attached the instance directly to the dom element using an expando property.  Sometimes I have done both.

To get access to the `htmlwidget`, we can use `HTMLWidgets.getInstance(document.getElementByClassName('sunburst')[0])`, and then manipulate away using `instance`, `renderValue`, and `resize`.

You also might be interested in this post [Look Ma no R](http://www.buildingwidgets.com/blog/2016/8/4/htmlwidgets-look-ma-no-r).

**Comment by GiovanninoPaneEvino** [comment]
@timelyportfolio 
I did not know about the function HTMLWidgets.getInstance() - Thanks a lot for the answer, lots of food for brain now :-)
