### ISSUE TITLE
on.click event  + colour question

### ISSUE THREAD

**Issue by NovasTaylor** [timelyportfolio/sunburstR#26]
Is it possible to have on.click events for the Sunburst sections, like can be coded in D3?
    .on("click", function (d) {
                 <action taken here>
                });
 I want to code a URL into the action based on values in the data, so I can drill down into the population of values represented in that section of the Sunburst. 

A second question: How is colour assigned to the categories in the Sunburst? Is it based on frequency count of the categories? Can it be set manually, to assign colours directly to categories, regardless of their order?

Thanks again for this excellent sunburst.  

Tim

**Comment by timelyportfolio** [comment]
### colour

In terms of colour, see #25 and let me know if you need any more help.  I hope to get this better documented soon.

### event handling

Also poorly documented, but I dispatch `mouseover/mouseout` and `click` with an array representing the path, so these can be accessed.  I will include a quick example below.  For a shiny example, see `?sunburstR::add_shiny`.

```
library(sunburstR)

# read in sample visit-sequences.csv data provided in source
#   https://gist.github.com/kerryrodden/7090426#file-visit-sequences-csv
sequences <- read.csv(
  system.file("examples/visit-sequences.csv",package="sunburstR")
  ,header = FALSE
  ,stringsAsFactors = FALSE
)

sb <- sunburst(sequences)

sb$x$tasks <- list(
  htmlwidgets::JS(
"
function(){
  //debugger;

  this.instance.chart.on('click',function(d){
    alert(d);
  });
}
"    
  )
)

sb
```

**Comment by timelyportfolio** [comment]
@NovasTaylor this http://timelyportfolio.github.io/sunburstR/example_baseball.html contains another example of event handling

**Comment by tyjselina** [comment]
Hello, @timelyportfolio , in the example you gave above, 
 this.instance.chart.on('click',function(d){
    alert(d);
  })
If we want to direct to a url, would open.window statement work?

Another question is: for the above link,  http://timelyportfolio.github.io/sunburstR/example_baseball.html,
I copied the code under title "Use sunburst event" to Rstudio, which doesn't give me the link for the hovered path.  Do you have any idea about it? I appreciate your help.

Selina

**Comment by timelyportfolio** [comment]
@tyjselina,

### `window.open` on.click

Yes, that should work fine, but you will need to generate the url unless it has been added in the `data` of the node.  You could use a reference table or build it up as in [lines](https://github.com/timelyportfolio/sunburstR/blame/master/inst/examples/example_baseball.Rmd#L118-L124).  I know I have another non-sunburst example somewhere, but I could not find it.  If you have trouble,  post some code and I'll try to help.

### use sunburst event error

I am not sure, since this still works for me.  Do you get an error on the R side?  If not, what happens when you do <F12> or <CTRL>+ <Shift> + i in Chrome. Do you see an error in the console?

**Comment by tyjselina** [comment]
Thanks, @timelyportfolio 
For the example you showed me above, instead of Mouseover event, I want to have Click event on Sunburst chart to redirect me to a URL,  I am trying to code as following:

sb$x$tasks <- list(htmlwidgets::JS(
  '
function(){
  this.instance.chart.on("click",clicked);
  var action = %s;
  function clicked(d){
  var games = action.filter(function(evt){
  return evt.event === d.join("-");
  });
  window.open(games.map(function(){
        return [
  "<a href=\'http://www.google.com",
  "</a><br/>"
  ]
  })
  );
  }
  
'
))

But still have some trouble, so could you help me take a look? 
Many thanks to your help!

Selina

**Comment by timelyportfolio** [comment]
I think this is "solved".  Please reopen if not.  Thanks for the issue.
