### ISSUE TITLE
Title or Sub-title of the plot

### ISSUE THREAD

**Issue by mashranga** [timelyportfolio/sunburstR#52]
How to add title or sub title of the plot ?

**Comment by cjyetman** [comment]
The `sunburstR` package does not have that functionality built-in. You could achieve something like that by using `htmlwidgets::prependContent()`, for instance, to add header text to the `htmlwidget` before displaying it, like this...
```r
library(htmltools)
library(htmlwidgets)
library(sunburstR)

sequences <- read.csv(
  system.file("examples/visit-sequences.csv",package="sunburstR")
  ,header = FALSE
  ,stringsAsFactors = FALSE
)[1:100,]

sn <- sunburst(sequences)
sn <- htmlwidgets::prependContent(sn, htmltools::h1("My Large Title"))
sn <- htmlwidgets::prependContent(sn, htmltools::h3("My Small Title"))
sn
```

**Comment by timelyportfolio** [comment]
Thanks @cjyetman!

**Comment by ajayram198** [comment]
@cjyetman When I try to do render the sunburst title plot in Shiny using the approach that you have suggested above, I m getting this warning
`Warning in renderWidget(instance) :
  Ignoring prepended content; prependContent can't be used in a Shiny render call`

Any idea how to resolve this?

**Comment by cjyetman** [comment]
No idea. Maybe if you provide a reproducible example I could figure it out.

**Comment by ajayram198** [comment]
Hi, please find enclose a reproducible example Shiny app.
`library(shiny)
library(sunburstR)
library(htmltools)
library(htmlwidgets)

sunburst_data <- read.csv("SunburstData.csv",header = T, stringsAsFactors = FALSE)

ui <- fluidPage(
  box(width=12,sunburstOutput("SunburstFigure"))
)

server <- function(input, output, session) {
  
  output$SunburstFigure <- renderSunburst({
    
    sn <- sunburst(sunburst_data)
    sn <- htmlwidgets::prependContent(sn, htmltools::h1("My Large Title"))
    sn <- htmlwidgets::prependContent(sn, htmltools::h3("My Small Title"))
    sn
  })
  
}

shinyApp(ui, server)`

Please find attached the data  that was used to generate the Sunburst plot. Since uploading CSV is not possible I am attaching an excel file containing the data. Could you please first convert it to csv and then run the code above?

And when I run this code I dont get the title on the Sunburst plot, instead I get this error:

`Warning in renderWidget(instance) :
  Ignoring prepended content; prependContent can't be used in a Shiny render call
`
Regards,
ajayram198
[SunburstData.xlsx](https://github.com/timelyportfolio/sunburstR/files/3127536/SunburstData.xlsx)

**Comment by cjyetman** [comment]
The docs for `htmlwidgets::prependContent` say "These functions are NOT supported when running in a Shiny widget rendering function, and will result in a warning if used in that context."... so maybe you can add a title using shiny functions?

**Comment by ajayram198** [comment]
ok,, So outside of the Sunburst function we can use h3 or box for header right?

**Comment by cjyetman** [comment]
I don't know... that's a question for the [Shiny folks](https://github.com/rstudio/shiny)

**Comment by ajayram198** [comment]
ok.. will enquire there, Thanks for the help!!
