### ISSUE TITLE
font size for inner circle text

### ISSUE THREAD

**Issue by dockstreet** [timelyportfolio/sunburstR#72]
Hi - can the font size be changed for the inner circle text?

**Comment by timelyportfolio** [comment]
@dockstreet, `css` will probably be the best way to style the explanation.  The text resides in a `div` with class `.sunburst-explanation`.

![image](https://user-images.githubusercontent.com/837910/41071969-92c02780-69c0-11e8-92bd-1c57f2bd5a80.png)

Since I am not sure what you are trying to achieve, here is just some made up styling.

```
library(sunburstR)

sequences <- read.csv(
  system.file("examples/visit-sequences.csv",package="sunburstR")
  ,header = FALSE
  ,stringsAsFactors = FALSE
)[1:100,]

sb <- sunburst(sequences)

htmlwidgets::prependContent(
  sb,
  htmltools::tags$style("
  .sunburst .sunburst-explanation {
    font-style: bold;
    font-size: 3em;
    color: green;
  }")
)
```

I will warn though that this will affect all sunbursts on a page.  See https://github.com/ramnathv/htmlwidgets/issues/231 for some discussion on being more specific.  I hope this helps.

**Comment by dockstreet** [comment]
Perfect! thanks so much this works like a charm!
