### ISSUE TITLE
The "-end" marker is being included in the path sequence output.

### ISSUE THREAD

**Issue by jrangeles** [timelyportfolio/sunburstR#8]
The "-end" marker is being shown in my chart. Based on Kerry Rodden's CSV format instructions, shouldn't the '-end" marker just serve as an indicator to distinguish a true end point? I believe the last path sequence to be shown should be the one before the "-end" marker.

If this is not an error. Is there a way to hide the "-end" marker and remove it from the path sequence? Initially I tried to run the data without the "-end" marker, but it doesn't render the chart without it.

You can view a sample of my data here:
https://github.com/jrangeles/Path-Sequence/blob/master/sequences_overview.csv

**Comment by timelyportfolio** [comment]
`-end` is intentionally shown to differentiate true end from arbitrarily chopped end points.  I'm sure there is a way to hide `-end` around these [lines](https://github.com/timelyportfolio/sunburstR/blob/master/inst/htmlwidgets/sunburst.js#L245-L249), but for me to do will be probably end of the week.  Any volunteers?

**Comment by jrangeles** [comment]
Can you explain then why my data doesn't work without `end-` in the path sequence? 
The initial data I had worked without the need of the `-end` mark, so I find it strange that simplifying the initial data and excluding redundant steps causes the chart not to rendered.

I don't have much JS experience so I'm not sure how to modify the code. Though I'm open to work on it if you could guide me what needs to be done.

**Comment by timelyportfolio** [comment]
Unfortunately, I honestly don't remember.  Guiding will take as long or longer than answering.  Just don't have the time over the next couple days.

**Comment by timelyportfolio** [comment]
@jrangeles, the reason you need a `-end` is explained in the original [Gist](http://bl.ocks.org/kerryrodden/7090426).

```
every sequence should have an "end" marker as the last element, unless it has been truncated because it is longer than the maximum sequence length (6, in the example). The purpose of the "end" marker is to distinguish a true end point (e.g. the user left the site) from an end point that has been forced by truncation.
```

**Comment by timelyportfolio** [comment]
@jrangeles feel free to reopen if you don't think this is resolved.  Closing in prep for CRAN submission.

**Comment by timelyportfolio** [comment]
Here is one way of hiding `end` https://github.com/timelyportfolio/sunburstR/issues/21#issuecomment-239540652 if you would like.  Let me know if you would like me to make a helper function or just making the default behavior.

**Comment by sco-lo-digital** [comment]
Kent - I think a great default behaviour would be ie DisplayEnd = FALSE as a parameter to the function `sunburst()`.   This allows control, but avoids confusion pertaining to the requirement that the data itself contain "end" at the end of each sequence string. In other words, I'm of the mind that if it is in the data, it should show up the same way by default in the visualization. The option to "clean it up" would be very welcome indeed 

I also think it would be helpful in the ?sunburst to elucidate the required form of the input data. something like  "sunburst takes as input a two column data frame of the form: 1.) sequence patterns separated by "-" and terminating with "end"  and 2.) the relative frequency with which this pattern occurs. "

Thanks for another great tool. This is really helping us explore data in a way we certainly otherwise would not have been able to!
